"""
Fortune 500 Companies - Full 500 List (2024 Rankings)
Corporate URLs and subpages for structural analysis scraping.
"""

COMPANIES = [
    # ══════════════════════════════════════════════
    # TOP 50 (existing, verified URLs)
    # ══════════════════════════════════════════════
    ("walmart", "Walmart", 1, "https://corporate.walmart.com", ["/about", "/purpose", "/leadership"]),
    ("amazon", "Amazon", 2, "https://www.aboutamazon.com", ["/about-us", "/news"]),
    ("apple", "Apple", 3, "https://www.apple.com", ["/leadership", "/environment", "/privacy"]),
    ("unitedhealth", "UnitedHealth Group", 4, "https://www.unitedhealthgroup.com", ["/about", "/people-and-businesses"]),
    ("berkshire-hathaway", "Berkshire Hathaway", 5, "https://www.berkshirehathaway.com", []),
    ("cvs-health", "CVS Health", 6, "https://www.cvshealth.com", ["/about", "/about/our-strategy"]),
    ("exxonmobil", "ExxonMobil", 7, "https://corporate.exxonmobil.com", ["/about", "/who-we-are"]),
    ("alphabet", "Alphabet (Google)", 8, "https://about.google", ["/intl/en/", "/our-story/"]),
    ("mckesson", "McKesson", 9, "https://www.mckesson.com", ["/about", "/about/our-company"]),
    ("amerisourcebergen", "Cencora", 10, "https://www.cencora.com", ["/about", "/about-us"]),
    ("costco", "Costco", 11, "https://www.costco.com/about.html", ["/sustainability-introduction.html"]),
    ("microsoft", "Microsoft", 12, "https://www.microsoft.com/en-us/about", ["/", "/leadership"]),
    ("cigna", "Cigna", 13, "https://www.cigna.com", ["/about-us", "/about-us/company-profile"]),
    ("cardinal-health", "Cardinal Health", 14, "https://www.cardinalhealth.com", ["/about"]),
    ("chevron", "Chevron", 15, "https://www.chevron.com", ["/who-we-are", "/sustainability"]),
    ("marathon-petroleum", "Marathon Petroleum", 16, "https://www.marathonpetroleum.com", ["/About/"]),
    ("jpmorgan-chase", "JPMorgan Chase", 17, "https://www.jpmorganchase.com", ["/about"]),
    ("fannie-mae", "Fannie Mae", 18, "https://www.fanniemae.com", ["/about-us"]),
    ("centene", "Centene", 19, "https://www.centene.com", ["/who-we-are/about-us"]),
    ("kroger", "Kroger", 20, "https://www.thekrogerco.com", ["/about-kroger"]),
    ("walgreens", "Walgreens Boots Alliance", 21, "https://www.walgreensbootsalliance.com", ["/about"]),
    ("bank-of-america", "Bank of America", 22, "https://about.bankofamerica.com", ["/our-company"]),
    ("phillips-66", "Phillips 66", 23, "https://www.phillips66.com", ["/about"]),
    ("ford", "Ford Motor", 24, "https://corporate.ford.com", ["/about", "/leadership"]),
    ("general-motors", "General Motors", 25, "https://www.gm.com", ["/company/about-gm"]),
    ("verizon", "Verizon", 26, "https://www.verizon.com/about", ["/our-company"]),
    ("att", "AT&T", 27, "https://about.att.com", ["/story"]),
    ("comcast", "Comcast", 28, "https://corporate.comcast.com", ["/company"]),
    ("meta", "Meta Platforms", 29, "https://about.meta.com", ["/company-info"]),
    ("elevance-health", "Elevance Health", 30, "https://www.elevancehealth.com", ["/who-we-are"]),
    ("home-depot", "Home Depot", 31, "https://corporate.homedepot.com", ["/about/"]),
    ("valero", "Valero Energy", 32, "https://www.valero.com", ["/about"]),
    ("dell", "Dell Technologies", 33, "https://www.dell.com/en-us/dt/corporate/about-us.htm", []),
    ("unitedparcel", "UPS", 34, "https://about.ups.com", ["/who-we-are"]),
    ("target", "Target", 35, "https://corporate.target.com", ["/about"]),
    ("pfizer", "Pfizer", 36, "https://www.pfizer.com", ["/about", "/about/leadership"]),
    ("state-farm", "State Farm", 37, "https://www.statefarm.com/about-us", ["/company-overview"]),
    ("johnson-johnson", "Johnson & Johnson", 38, "https://www.jnj.com", ["/about-jnj"]),
    ("humana", "Humana", 39, "https://www.humana.com/about", ["/leadership"]),
    ("freddie-mac", "Freddie Mac", 40, "https://www.freddiemac.com", ["/about"]),
    ("procter-gamble", "Procter & Gamble", 41, "https://us.pg.com", ["/our-brands", "/our-company"]),
    ("tesla", "Tesla", 42, "https://www.tesla.com", ["/about", "/impact"]),
    ("general-electric", "GE Aerospace", 43, "https://www.geaerospace.com", ["/company/about-us"]),
    ("disney", "Walt Disney", 44, "https://thewaltdisneycompany.com", ["/about/"]),
    ("raytheon", "RTX", 45, "https://www.rtx.com", ["/who-we-are"]),
    ("abbvie", "AbbVie", 46, "https://www.abbvie.com", ["/about"]),
    ("caterpillar", "Caterpillar", 47, "https://www.caterpillar.com", ["/company"]),
    ("ibm", "IBM", 48, "https://www.ibm.com", ["/about"]),
    ("lockheed-martin", "Lockheed Martin", 49, "https://www.lockheedmartin.com", ["/about"]),
    ("boeing", "Boeing", 50, "https://www.boeing.com", ["/company"]),

    # ══════════════════════════════════════════════
    # 51-100
    # ══════════════════════════════════════════════
    ("anthem", "Anthem", 51, "https://www.antheminc.com", ["/about"]),
    ("citigroup", "Citigroup", 52, "https://www.citigroup.com", ["/about"]),
    ("sysco", "Sysco", 53, "https://www.sysco.com", ["/about-sysco"]),
    ("merck", "Merck", 54, "https://www.merck.com", ["/about", "/company-overview"]),
    ("wells-fargo", "Wells Fargo", 55, "https://www.wellsfargo.com/about", ["/company"]),
    ("conocophillips", "ConocoPhillips", 56, "https://www.conocophillips.com", ["/about-us"]),
    ("pepsi", "PepsiCo", 57, "https://www.pepsico.com", ["/about", "/about/mission-and-vision"]),
    ("archer-daniels", "Archer Daniels Midland", 58, "https://www.adm.com", ["/our-company"]),
    ("intel", "Intel", 59, "https://www.intel.com/content/www/us/en/company-overview/company-overview.html", []),
    ("goldman-sachs", "Goldman Sachs", 60, "https://www.goldmansachs.com", ["/about-us"]),
    ("cisco", "Cisco Systems", 61, "https://www.cisco.com", ["/c/en/us/about.html"]),
    ("lowes", "Lowe's", 62, "https://corporate.lowes.com", ["/about"]),
    ("nike", "Nike", 63, "https://about.nike.com", []),
    ("morgan-stanley", "Morgan Stanley", 64, "https://www.morganstanley.com", ["/about-us"]),
    ("hp-inc", "HP Inc.", 65, "https://www.hp.com/us-en/about.html", []),
    ("tyson", "Tyson Foods", 66, "https://www.tysonfoods.com", ["/who-we-are"]),
    ("disney-media", "Warner Bros. Discovery", 67, "https://wbd.com", ["/about"]),
    ("oracle", "Oracle", 68, "https://www.oracle.com/corporate", []),
    ("dow", "Dow", 69, "https://www.dow.com", ["/about-dow"]),
    ("thermo-fisher", "Thermo Fisher Scientific", 70, "https://www.thermofisher.com/us/en/home/about-us.html", []),
    ("honeywell", "Honeywell", 71, "https://www.honeywell.com", ["/us/en/company/about-us"]),
    ("enterprise-products", "Enterprise Products Partners", 72, "https://www.enterpriseproducts.com", ["/about-us"]),
    ("energy-transfer", "Energy Transfer", 73, "https://www.energytransfer.com", ["/about"]),
    ("aetna", "Aetna (CVS)", 74, "https://www.aetna.com", ["/about-us"]),
    ("american-express", "American Express", 75, "https://www.americanexpress.com/en-us/company", []),
    ("albertsons", "Albertsons", 76, "https://www.albertsonscompanies.com", ["/about-us"]),
    ("progressive", "Progressive", 77, "https://www.progressive.com/about", []),
    ("disney-parks", "Disney Parks", 78, "https://sites.disney.com/lifeatdisney", []),
    ("hca-healthcare", "HCA Healthcare", 79, "https://hcahealthcare.com", ["/about"]),
    ("plains-all-american", "Plains All American Pipeline", 80, "https://www.plainsallamerican.com", ["/about-us"]),
    ("publix", "Publix", 81, "https://corporate.publix.com", ["/about-publix"]),
    ("travelers", "Travelers", 82, "https://www.travelers.com/about-travelers", []),
    ("liberty-mutual", "Liberty Mutual", 83, "https://www.libertymutual.com/about-lm", []),
    ("td-synnex", "TD Synnex", 84, "https://www.tdsynnex.com", ["/about"]),
    ("us-foods", "US Foods", 85, "https://www.usfoods.com", ["/about-us"]),
    ("northrop-grumman", "Northrop Grumman", 86, "https://www.northropgrumman.com", ["/who-we-are"]),
    ("penske", "Penske Automotive Group", 87, "https://www.penskeautomotive.com", ["/about"]),
    ("nucor", "Nucor", 88, "https://www.nucor.com", ["/about"]),
    ("deere", "Deere & Company", 89, "https://www.deere.com/en/our-company", ["/about-john-deere/"]),
    ("qualcomm", "Qualcomm", 90, "https://www.qualcomm.com/company", ["/about"]),
    ("world-fuel", "World Fuel Services", 91, "https://www.world-fuel.com", ["/about-us"]),
    ("starbucks", "Starbucks", 92, "https://stories.starbucks.com", ["/about"]),
    ("general-dynamics", "General Dynamics", 93, "https://www.gd.com", ["/about"]),
    ("avnet", "Avnet", 94, "https://www.avnet.com", ["/wps/portal/us/about-avnet"]),
    ("chs", "CHS", 95, "https://www.chsinc.com", ["/about-us"]),
    ("capital-one", "Capital One", 96, "https://www.capitalone.com/about", []),
    ("best-buy", "Best Buy", 97, "https://corporate.bestbuy.com", ["/about"]),
    ("merck-animal", "Organon", 98, "https://www.organon.com", ["/about"]),
    ("bristol-myers", "Bristol-Myers Squibb", 99, "https://www.bms.com", ["/about-us"]),
    ("united-airlines", "United Airlines Holdings", 100, "https://www.united.com/en-us/fly/company", []),

    # ══════════════════════════════════════════════
    # 101-200
    # ══════════════════════════════════════════════
    ("delta-air", "Delta Air Lines", 101, "https://www.delta.com/us/en/about-delta/overview", []),
    ("coca-cola", "Coca-Cola", 102, "https://www.coca-colacompany.com", ["/about-us", "/our-company"]),
    ("mondelez", "Mondelez International", 103, "https://www.mondelezinternational.com", ["/About-Us"]),
    ("allstate", "Allstate", 104, "https://www.allstate.com/about", []),
    ("kraft-heinz", "Kraft Heinz", 105, "https://www.kraftheinzcompany.com", ["/about-us"]),
    ("micron", "Micron Technology", 106, "https://www.micron.com", ["/about"]),
    ("3m", "3M", 107, "https://www.3m.com", ["/3M/en_US/company-us/about-3m"]),
    ("abbvie-pharm", "AbbVie Pharmaceuticals", 108, "https://www.abbvie.com", ["/science", "/our-company"]),
    ("american-airlines", "American Airlines Group", 109, "https://www.aa.com/i18n/customer-service/about-us/about-us.jsp", []),
    ("us-bancorp", "U.S. Bancorp", 110, "https://www.usbank.com/about-us-bank.html", []),
    ("nationwide", "Nationwide", 111, "https://www.nationwide.com/personal/about-us", []),
    ("arrow-electronics", "Arrow Electronics", 112, "https://www.arrow.com", ["/company"]),
    ("new-york-life", "New York Life", 113, "https://www.newyorklife.com/about", []),
    ("performance-food", "Performance Food Group", 114, "https://www.pfgc.com", ["/about"]),
    ("applied-materials", "Applied Materials", 115, "https://www.appliedmaterials.com", ["/company"]),
    ("raytheon-tech", "L3Harris Technologies", 116, "https://www.l3harris.com", ["/about"]),
    ("molina", "Molina Healthcare", 117, "https://www.molinahealthcare.com", ["/about"]),
    ("salesforce", "Salesforce", 118, "https://www.salesforce.com/company", ["/about-us"]),
    ("pg-e", "PG&E", 119, "https://www.pge.com/en/about.html", []),
    ("nvidia", "NVIDIA", 120, "https://www.nvidia.com/en-us/about-nvidia", []),
    ("fidelity", "Fidelity Investments", 121, "https://www.fidelity.com/about-fidelity/our-company", []),
    ("dollar-general", "Dollar General", 122, "https://www.dollargeneral.com/about-us.html", []),
    ("charter-communications", "Charter Communications", 123, "https://corporate.charter.com", ["/about"]),
    ("pnc-financial", "PNC Financial", 124, "https://www.pnc.com/en/about-pnc.html", []),
    ("farmers-insurance", "Farmers Insurance", 125, "https://www.farmers.com/about-us", []),
    ("southwest-airlines", "Southwest Airlines", 126, "https://www.southwestairlinesonereport.com", ["/about-southwest"]),
    ("broadcom", "Broadcom", 127, "https://www.broadcom.com", ["/company"]),
    ("southern-company", "Southern Company", 128, "https://www.southerncompany.com", ["/about-us"]),
    ("duke-energy", "Duke Energy", 129, "https://www.duke-energy.com/our-company", ["/about-us"]),
    ("abbottlabs", "Abbott Laboratories", 130, "https://www.abbott.com", ["/about-abbott"]),
    ("exelon", "Exelon", 131, "https://www.exeloncorp.com", ["/company"]),
    ("colgate", "Colgate-Palmolive", 132, "https://www.colgatepalmolive.com", ["/who-we-are"]),
    ("nextera", "NextEra Energy", 133, "https://www.nexteraenergy.com", ["/company"]),
    ("jabil", "Jabil", 134, "https://www.jabil.com", ["/about-us"]),
    ("conocophillips-2", "Cheniere Energy", 135, "https://www.cheniere.com", ["/about"]),
    ("international-paper", "International Paper", 136, "https://www.internationalpaper.com", ["/company"]),
    ("marsh-mclennan", "Marsh McLennan", 137, "https://www.marshmclennan.com", ["/about"]),
    ("truist", "Truist Financial", 138, "https://www.truist.com/who-we-are", ["/about-truist"]),
    ("tyson-foods", "Cargill", 139, "https://www.cargill.com", ["/about"]),
    ("sempra", "Sempra", 140, "https://www.sempra.com", ["/about-us"]),
    ("te-connectivity", "TE Connectivity", 141, "https://www.te.com", ["/about-te"]),
    ("emerson", "Emerson Electric", 142, "https://www.emerson.com", ["/about-us"]),
    ("whirlpool", "Whirlpool", 143, "https://www.whirlpoolcorp.com", ["/about"]),
    ("danaher", "Danaher", 144, "https://www.danaher.com", ["/about"]),
    ("baxter", "Baxter International", 145, "https://www.baxter.com", ["/about"]),
    ("automatic-data", "ADP", 146, "https://www.adp.com/about-adp.aspx", []),
    ("dupont", "DuPont", 147, "https://www.dupont.com", ["/about"]),
    ("lear", "Lear Corporation", 148, "https://www.lear.com", ["/about"]),
    ("us-steel", "United States Steel", 149, "https://www.ussteel.com", ["/about-us"]),
    ("genuine-parts", "Genuine Parts", 150, "https://www.genpt.com", ["/about"]),
    ("kimberly-clark", "Kimberly-Clark", 151, "https://www.kimberly-clark.com", ["/company"]),
    ("waste-management", "Waste Management", 152, "https://www.wm.com", ["/about"]),
    ("ecolab", "Ecolab", 153, "https://www.ecolab.com", ["/about"]),
    ("dominion-energy", "Dominion Energy", 154, "https://www.dominionenergy.com/our-company", ["/about-us"]),
    ("general-mills", "General Mills", 155, "https://www.generalmills.com", ["/about-us"]),
    ("halliburton", "Halliburton", 156, "https://www.halliburton.com", ["/about-us"]),
    ("schlumberger", "SLB", 157, "https://www.slb.com", ["/about"]),
    ("becton-dickinson", "Becton Dickinson", 158, "https://www.bd.com", ["/about-bd"]),
    ("nordstrom", "Nordstrom", 159, "https://press.nordstrom.com/about", []),
    ("ross", "Ross Stores", 160, "https://corp.rossstores.com", ["/about-us"]),
    ("aflac", "Aflac", 161, "https://www.aflac.com/about-aflac", []),
    ("devon-energy", "Devon Energy", 162, "https://www.devonenergy.com", ["/about"]),
    ("corning", "Corning", 163, "https://www.corning.com", ["/about-us"]),
    ("xcel-energy", "Xcel Energy", 164, "https://www.xcelenergy.com", ["/company"]),
    ("lincoln-national", "Lincoln National", 165, "https://www.lincolnfinancial.com", ["/public/aboutus"]),
    ("hershey", "Hershey", 166, "https://www.thehersheycompany.com", ["/about"]),
    ("cummins", "Cummins", 167, "https://www.cummins.com", ["/company"]),
    ("paccar", "PACCAR", 168, "https://www.paccar.com", ["/about-us"]),
    ("parker-hannifin", "Parker Hannifin", 169, "https://www.parker.com", ["/about-us"]),
    ("textron", "Textron", 170, "https://www.textron.com", ["/About"]),
    ("aramark", "Aramark", 171, "https://www.aramark.com", ["/about"]),
    ("visa", "Visa", 172, "https://usa.visa.com/about-visa.html", []),
    ("mastercard", "Mastercard", 173, "https://www.mastercard.us/en-us/vision/who-we-are.html", []),
    ("paypal", "PayPal", 174, "https://about.pypl.com", ["/about"]),
    ("adobe", "Adobe", 175, "https://www.adobe.com/about-adobe.html", []),
    ("intuit", "Intuit", 176, "https://www.intuit.com/company", []),
    ("booking", "Booking Holdings", 177, "https://www.bookingholdings.com", ["/about"]),
    ("servicenow", "ServiceNow", 178, "https://www.servicenow.com/company.html", []),
    ("uber", "Uber Technologies", 179, "https://www.uber.com/us/en/about", []),
    ("airbnb", "Airbnb", 180, "https://news.airbnb.com/about-us", []),
    ("block", "Block (Square)", 181, "https://block.xyz", ["/about"]),
    ("snap", "Snap Inc.", 182, "https://snap.com/en-US", []),
    ("spotify", "Spotify", 183, "https://www.lifeatspotify.com", ["/about"]),
    ("doordash", "DoorDash", 184, "https://about.doordash.com", ["/about"]),
    ("palantir", "Palantir Technologies", 185, "https://www.palantir.com/about", []),
    ("twilio", "Twilio", 186, "https://www.twilio.com/company", []),
    ("crowdstrike", "CrowdStrike", 187, "https://www.crowdstrike.com/about-crowdstrike", []),
    ("palo-alto", "Palo Alto Networks", 188, "https://www.paloaltonetworks.com/company", []),
    ("fortinet", "Fortinet", 189, "https://www.fortinet.com/corporate/about-us", []),
    ("snowflake", "Snowflake", 190, "https://www.snowflake.com/about", []),
    ("datadog", "Datadog", 191, "https://www.datadoghq.com/about", []),
    ("trade-desk", "The Trade Desk", 192, "https://www.thetradedesk.com/us/about-us", []),
    ("zillow", "Zillow Group", 193, "https://www.zillowgroup.com", ["/about"]),
    ("coinbase", "Coinbase", 194, "https://www.coinbase.com/about", []),
    ("rivian", "Rivian", 195, "https://rivian.com/about", []),
    ("lucid", "Lucid Group", 196, "https://lucidmotors.com/company", []),
    ("draftkings", "DraftKings", 197, "https://www.draftkings.com/about", []),
    ("toast", "Toast", 198, "https://pos.toasttab.com/about", []),
    ("mongodb", "MongoDB", 199, "https://www.mongodb.com/company", []),
    ("atlassian", "Atlassian", 200, "https://www.atlassian.com/company", []),

    # ══════════════════════════════════════════════
    # 201-300
    # ══════════════════════════════════════════════
    ("baker-hughes", "Baker Hughes", 201, "https://www.bakerhughes.com", ["/company"]),
    ("fluor", "Fluor Corporation", 202, "https://www.fluor.com", ["/about-fluor"]),
    ("mcdonalds", "McDonald's", 203, "https://corporate.mcdonalds.com", ["/about-us"]),
    ("tjx", "TJX Companies", 204, "https://www.tjx.com", ["/company"]),
    ("autozone", "AutoZone", 205, "https://www.autozone.com/company-information", []),
    ("cbre", "CBRE Group", 206, "https://www.cbre.com", ["/about-us"]),
    ("southwest-gas", "Southwest Gas", 207, "https://www.swgas.com", ["/about-us"]),
    ("consolidated-edison", "Consolidated Edison", 208, "https://www.conedison.com/en/about-us", []),
    ("edison-international", "Edison International", 209, "https://www.edison.com", ["/about"]),
    ("entergy", "Entergy", 210, "https://www.entergy.com", ["/about-entergy"]),
    ("firstenergy", "FirstEnergy", 211, "https://www.firstenergycorp.com", ["/about"]),
    ("ameren", "Ameren", 212, "https://www.ameren.com", ["/company"]),
    ("cms-energy", "CMS Energy", 213, "https://www.cmsenergy.com", ["/about"]),
    ("dte-energy", "DTE Energy", 214, "https://www.dteenergy.com/us/en/residential/about.html", []),
    ("centerpoint", "CenterPoint Energy", 215, "https://www.centerpointenergy.com/en-us/corporate/about-us", []),
    ("aes", "AES Corporation", 216, "https://www.aes.com", ["/about"]),
    ("evergy", "Evergy", 217, "https://www.evergy.com", ["/about-evergy"]),
    ("nrg-energy", "NRG Energy", 218, "https://www.nrg.com", ["/about"]),
    ("pinnacle-west", "Pinnacle West Capital", 219, "https://www.pinnaclewest.com", ["/about-us"]),
    ("alliant-energy", "Alliant Energy", 220, "https://www.alliantenergy.com", ["/about"]),
    ("williams", "Williams Companies", 221, "https://www.williams.com", ["/about-us"]),
    ("oneok", "ONEOK", 222, "https://www.oneok.com", ["/about-oneok"]),
    ("targa-resources", "Targa Resources", 223, "https://www.targaresources.com", ["/about"]),
    ("kinder-morgan", "Kinder Morgan", 224, "https://www.kindermorgan.com", ["/About-Us"]),
    ("coterra", "Coterra Energy", 225, "https://www.coteraenergy.com", ["/about"]),
    ("eog-resources", "EOG Resources", 226, "https://www.eogresources.com", ["/about"]),
    ("pioneer-natural", "Pioneer Natural Resources", 227, "https://www.pxd.com", ["/about-us"]),
    ("diamondback", "Diamondback Energy", 228, "https://www.diamondbackenergy.com", ["/about"]),
    ("hess", "Hess Corporation", 229, "https://www.hess.com", ["/about"]),
    ("marathon-oil", "Marathon Oil", 230, "https://www.marathonoil.com", ["/About"]),
    ("weyerhaeuser", "Weyerhaeuser", 231, "https://www.weyerhaeuser.com", ["/company"]),
    ("freeport-mcmoran", "Freeport-McMoRan", 232, "https://www.fcx.com", ["/about"]),
    ("newmont", "Newmont", 233, "https://www.newmont.com", ["/about-us"]),
    ("air-products", "Air Products", 234, "https://www.airproducts.com", ["/company"]),
    ("linde", "Linde", 235, "https://www.linde.com", ["/about-linde"]),
    ("ppg", "PPG Industries", 236, "https://www.ppg.com", ["/about"]),
    ("sherwin-williams", "Sherwin-Williams", 237, "https://corporate.sherwin-williams.com", ["/about"]),
    ("rpm-international", "RPM International", 238, "https://www.rpminc.com", ["/about"]),
    ("eastman-chemical", "Eastman Chemical", 239, "https://www.eastman.com", ["/Company/About-Eastman"]),
    ("celanese", "Celanese", 240, "https://www.celanese.com", ["/about"]),
    ("mosaic", "Mosaic Company", 241, "https://www.mosaicco.com", ["/about-us"]),
    ("cf-industries", "CF Industries", 242, "https://www.cfindustries.com", ["/about-cf"]),
    ("lyondellbasell", "LyondellBasell", 243, "https://www.lyondellbasell.com", ["/about-us"]),
    ("westlake", "Westlake Corporation", 244, "https://www.westlake.com", ["/about-us"]),
    ("packaging-corp", "Packaging Corp of America", 245, "https://www.packagingcorp.com", ["/about"]),
    ("sealed-air", "Sealed Air", 246, "https://www.sealedair.com", ["/company"]),
    ("graphic-packaging", "Graphic Packaging", 247, "https://www.graphicpkg.com", ["/about"]),
    ("avery-dennison", "Avery Dennison", 248, "https://www.averydennison.com", ["/company"]),
    ("ball-corp", "Ball Corporation", 249, "https://www.ball.com", ["/about-ball"]),
    ("crown-holdings", "Crown Holdings", 250, "https://www.crowncork.com", ["/about"]),

    # ══════════════════════════════════════════════
    # 251-350
    # ══════════════════════════════════════════════
    ("huntsman", "Huntsman Corporation", 251, "https://www.huntsman.com", ["/about"]),
    ("olin", "Olin Corporation", 252, "https://www.olin.com", ["/About-Olin"]),
    ("ashland", "Ashland Global", 253, "https://www.ashland.com", ["/about"]),
    ("cabot", "Cabot Corporation", 254, "https://www.cabotcorp.com", ["/company"]),
    ("albemarle", "Albemarle", 255, "https://www.albemarle.com", ["/about"]),
    ("illinois-tool", "Illinois Tool Works", 256, "https://www.itw.com", ["/about-itw"]),
    ("stanley-black", "Stanley Black & Decker", 257, "https://www.stanleyblackanddecker.com", ["/about"]),
    ("snap-on", "Snap-on", 258, "https://www.snapon.com", ["/about"]),
    ("dover", "Dover Corporation", 259, "https://www.dovercorporation.com", ["/about"]),
    ("roper-tech", "Roper Technologies", 260, "https://www.ropertech.com", ["/about-us"]),
    ("fortive", "Fortive", 261, "https://www.fortive.com", ["/about"]),
    ("ametek", "AMETEK", 262, "https://www.ametek.com", ["/about-ametek"]),
    ("xylem", "Xylem", 263, "https://www.xylem.com", ["/about-xylem"]),
    ("pentair", "Pentair", 264, "https://www.pentair.com", ["/about-us"]),
    ("watts-water", "Watts Water Technologies", 265, "https://www.watts.com", ["/About-Us"]),
    ("flowserve", "Flowserve", 266, "https://www.flowserve.com", ["/about-flowserve"]),
    ("graco", "Graco", 267, "https://www.graco.com", ["/about-us"]),
    ("nordson", "Nordson", 268, "https://www.nordson.com", ["/about"]),
    ("idex", "IDEX Corporation", 269, "https://www.idexcorp.com", ["/about"]),
    ("lincoln-electric", "Lincoln Electric", 270, "https://www.lincolnelectric.com", ["/company"]),
    ("hubbell", "Hubbell", 271, "https://www.hubbell.com", ["/about"]),
    ("acuity-brands", "Acuity Brands", 272, "https://www.acuitybrands.com", ["/about"]),
    ("regal-rexnord", "Regal Rexnord", 273, "https://www.regalrexnord.com", ["/about"]),
    ("wesco", "WESCO International", 274, "https://www.wesco.com", ["/about"]),
    ("fastenal", "Fastenal", 275, "https://www.fastenal.com/en/76/about-fastenal", []),
    ("msc-industrial", "MSC Industrial", 276, "https://www.mscdirect.com/company/about-us", []),
    ("wr-grainger", "W.W. Grainger", 277, "https://www.grainger.com/content/about-grainger", []),
    ("cintas", "Cintas", 278, "https://www.cintas.com", ["/company"]),
    ("unifirst", "UniFirst", 279, "https://www.unifirst.com", ["/about-us"]),
    ("rollins", "Rollins", 280, "https://www.rollins.com", ["/about"]),
    ("waste-connections", "Waste Connections", 281, "https://www.wasteconnections.com", ["/about-us"]),
    ("republic-services", "Republic Services", 282, "https://www.republicservices.com", ["/about-us"]),
    ("clean-harbors", "Clean Harbors", 283, "https://www.cleanharbors.com", ["/about"]),
    ("stericycle", "Stericycle", 284, "https://www.stericycle.com", ["/about-us"]),
    ("iron-mountain", "Iron Mountain", 285, "https://www.ironmountain.com", ["/about"]),
    ("copart", "Copart", 286, "https://www.copart.com/aboutcopart", []),
    ("lkq", "LKQ Corporation", 287, "https://www.lkqcorp.com", ["/about-us"]),
    ("pool-corp", "Pool Corporation", 288, "https://www.poolcorp.com", ["/about"]),
    ("siteone", "SiteOne Landscape Supply", 289, "https://www.siteone.com", ["/about-us"]),
    ("henry-schein", "Henry Schein", 290, "https://www.henryschein.com", ["/about"]),
    ("patterson", "Patterson Companies", 291, "https://www.pattersoncompanies.com", ["/about-us"]),
    ("mckesson-medical", "Owens & Minor", 292, "https://www.owens-minor.com", ["/about"]),
    ("medline", "Medline Industries", 293, "https://www.medline.com", ["/about-us"]),
    ("stryker", "Stryker", 294, "https://www.stryker.com", ["/about"]),
    ("zimmer-biomet", "Zimmer Biomet", 295, "https://www.zimmerbiomet.com", ["/about"]),
    ("boston-scientific", "Boston Scientific", 296, "https://www.bostonscientific.com", ["/about-us"]),
    ("edwards-lifesciences", "Edwards Lifesciences", 297, "https://www.edwards.com", ["/about-us"]),
    ("resmed", "ResMed", 298, "https://www.resmed.com", ["/about"]),
    ("intuitive-surgical", "Intuitive Surgical", 299, "https://www.intuitive.com", ["/about-us"]),
    ("agilent", "Agilent Technologies", 300, "https://www.agilent.com", ["/about"]),

    # ══════════════════════════════════════════════
    # 301-400
    # ══════════════════════════════════════════════
    ("illumina", "Illumina", 301, "https://www.illumina.com", ["/company.html"]),
    ("bio-rad", "Bio-Rad Laboratories", 302, "https://www.bio-rad.com", ["/en-us/corporate/about-bio-rad"]),
    ("waters", "Waters Corporation", 303, "https://www.waters.com", ["/about-waters"]),
    ("mettler-toledo", "Mettler-Toledo", 304, "https://www.mt.com", ["/us/en/home/site_content/about_us.html"]),
    ("keysight", "Keysight Technologies", 305, "https://www.keysight.com", ["/us/en/about.html"]),
    ("teledyne", "Teledyne Technologies", 306, "https://www.teledyne.com", ["/about-us"]),
    ("trimble", "Trimble", 307, "https://www.trimble.com", ["/about"]),
    ("zebra-tech", "Zebra Technologies", 308, "https://www.zebra.com", ["/us/en/about-zebra.html"]),
    ("cognizant", "Cognizant", 309, "https://www.cognizant.com", ["/about-cognizant"]),
    ("accenture", "Accenture", 310, "https://www.accenture.com", ["/us-en/about/company-index"]),
    ("infosys", "Infosys (US)", 311, "https://www.infosys.com", ["/about.html"]),
    ("epam", "EPAM Systems", 312, "https://www.epam.com", ["/about"]),
    ("gartner", "Gartner", 313, "https://www.gartner.com", ["/en/about"]),
    ("verisk", "Verisk Analytics", 314, "https://www.verisk.com", ["/about"]),
    ("iqvia", "IQVIA", 315, "https://www.iqvia.com", ["/about-us"]),
    ("fair-isaac", "FICO", 316, "https://www.fico.com", ["/about"]),
    ("jack-henry", "Jack Henry & Associates", 317, "https://www.jackhenry.com", ["/who-we-serve"]),
    ("fis", "FIS", 318, "https://www.fisglobal.com", ["/about-us"]),
    ("fiserv", "Fiserv", 319, "https://www.fiserv.com", ["/about"]),
    ("global-payments", "Global Payments", 320, "https://www.globalpayments.com", ["/about-us"]),
    ("fleetcor", "FLEETCOR Technologies", 321, "https://www.fleetcor.com", ["/about"]),
    ("wex", "WEX", 322, "https://www.wexinc.com", ["/about"]),
    ("blackrock", "BlackRock", 323, "https://www.blackrock.com/corporate/about-us", []),
    ("state-street", "State Street", 324, "https://www.statestreet.com", ["/about"]),
    ("bny-mellon", "BNY Mellon", 325, "https://www.bnymellon.com", ["/us/en/about-us.html"]),
    ("northern-trust", "Northern Trust", 326, "https://www.northerntrust.com", ["/about"]),
    ("t-rowe-price", "T. Rowe Price", 327, "https://www.troweprice.com/corporate/us/en/what-we-do.html", []),
    ("franklin-templeton", "Franklin Templeton", 328, "https://www.franklintempleton.com/about-us", []),
    ("invesco", "Invesco", 329, "https://www.invesco.com/corporate/about-us", []),
    ("legg-mason", "Eaton Vance", 330, "https://www.eatonvance.com", ["/about"]),
    ("principal", "Principal Financial", 331, "https://www.principal.com/about-us", []),
    ("unum", "Unum Group", 332, "https://www.unum.com/about", []),
    ("metlife", "MetLife", 333, "https://www.metlife.com/about-us", []),
    ("prudential", "Prudential Financial", 334, "https://www.prudential.com/about", []),
    ("aig", "AIG", 335, "https://www.aig.com/about-us", []),
    ("hartford", "Hartford Financial", 336, "https://www.thehartford.com/about-us", []),
    ("cna-financial", "CNA Financial", 337, "https://www.cna.com/web/guest/cna/about", []),
    ("markel", "Markel Corporation", 338, "https://www.markel.com", ["/about"]),
    ("erie-indemnity", "Erie Indemnity", 339, "https://www.erieinsurance.com/about-us", []),
    ("renaissancere", "RenaissanceRe", 340, "https://www.renre.com", ["/about"]),
    ("everest-re", "Everest Re Group", 341, "https://www.everestre.com", ["/about"]),
    ("arch-capital", "Arch Capital Group", 342, "https://www.archgroup.com", ["/about-us"]),
    ("globe-life", "Globe Life", 343, "https://www.globelifeinsurance.com", ["/about-us"]),
    ("chubb", "Chubb", 344, "https://www.chubb.com/us-en/about-chubb.html", []),
    ("cincinnati-fin", "Cincinnati Financial", 345, "https://www.cinfin.com/about-us", []),
    ("hanover-insurance", "Hanover Insurance Group", 346, "https://www.hanover.com", ["/about"]),
    ("w-r-berkley", "W.R. Berkley", 347, "https://www.wrberkley.com", ["/about-us"]),
    ("loews", "Loews Corporation", 348, "https://www.loews.com", ["/about"]),
    ("alleghany", "Alleghany Corporation", 349, "https://www.alleghany.com", ["/about"]),
    ("brown-brown", "Brown & Brown", 350, "https://www.bbinsurance.com", ["/about-us"]),

    # ══════════════════════════════════════════════
    # 351-450
    # ══════════════════════════════════════════════
    ("aon", "Aon", 351, "https://www.aon.com/home/about", []),
    ("willis-towers", "WTW", 352, "https://www.wtwco.com", ["/about-us"]),
    ("arthur-gallagher", "Arthur J. Gallagher", 353, "https://www.ajg.com", ["/about-us"]),
    ("assurant", "Assurant", 354, "https://www.assurant.com", ["/about-us"]),
    ("voya", "Voya Financial", 355, "https://www.voya.com", ["/about"]),
    ("raymond-james", "Raymond James", 356, "https://www.raymondjames.com/about-raymond-james", []),
    ("stifel", "Stifel Financial", 357, "https://www.stifel.com/about-stifel", []),
    ("jefferies", "Jefferies Financial Group", 358, "https://www.jefferies.com", ["/about"]),
    ("interactive-brokers", "Interactive Brokers", 359, "https://www.interactivebrokers.com/en/general/about.php", []),
    ("charles-schwab", "Charles Schwab", 360, "https://www.aboutschwab.com", ["/who-we-are"]),
    ("td-ameritrade", "TD Ameritrade", 361, "https://www.tdameritrade.com/about-us.html", []),
    ("ameriprise", "Ameriprise Financial", 362, "https://www.ameriprise.com/about", []),
    ("synchrony", "Synchrony Financial", 363, "https://www.synchrony.com/about-us.html", []),
    ("discover", "Discover Financial", 364, "https://www.discover.com/company", ["/about-discover"]),
    ("ally", "Ally Financial", 365, "https://www.ally.com/about", []),
    ("citizens-fin", "Citizens Financial Group", 366, "https://www.citizensbank.com/about-us.aspx", []),
    ("regions", "Regions Financial", 367, "https://www.regions.com/about-regions", []),
    ("keycorp", "KeyCorp", 368, "https://www.key.com/about", []),
    ("huntington", "Huntington Bancshares", 369, "https://www.huntington.com/About-Us", []),
    ("m-and-t", "M&T Bank", 370, "https://www3.mtb.com/about-us", []),
    ("fifth-third", "Fifth Third Bancorp", 371, "https://www.53.com/content/fifth-third/en/about.html", []),
    ("comerica", "Comerica", 372, "https://www.comerica.com/about-us.html", []),
    ("zions", "Zions Bancorporation", 373, "https://www.zionsbancorporation.com/about", []),
    ("cullen-frost", "Cullen/Frost Bankers", 374, "https://www.frostbank.com/about-frost", []),
    ("first-horizon", "First Horizon", 375, "https://www.firsthorizon.com/About-Us", []),
    ("webster", "Webster Financial", 376, "https://www.websterbank.com/about-webster", []),
    ("east-west", "East West Bancorp", 377, "https://www.eastwestbank.com/en/about-us", []),
    ("glacier", "Glacier Bancorp", 378, "https://www.glacierbancorp.com/about-us", []),
    ("columbia-banking", "Columbia Banking System", 379, "https://www.columbiabanking.com/about-us", []),
    ("wintrust", "Wintrust Financial", 380, "https://www.wintrust.com/about-us.html", []),
    ("hilton", "Hilton", 381, "https://www.hilton.com/en/corporate", ["/about"]),
    ("marriott", "Marriott International", 382, "https://www.marriott.com/about/default.mi", []),
    ("hyatt", "Hyatt Hotels", 383, "https://about.hyatt.com", []),
    ("wyndham", "Wyndham Hotels", 384, "https://www.wyndhamhotels.com/about-us", []),
    ("choice-hotels", "Choice Hotels", 385, "https://www.choicehotels.com/about", []),
    ("mgm", "MGM Resorts", 386, "https://www.mgmresorts.com/en/company.html", []),
    ("caesars", "Caesars Entertainment", 387, "https://www.caesars.com/corporate", ["/about"]),
    ("las-vegas-sands", "Las Vegas Sands", 388, "https://www.sands.com", ["/company"]),
    ("royal-caribbean", "Royal Caribbean", 389, "https://www.royalcaribbeangroup.com", ["/about"]),
    ("carnival", "Carnival Corporation", 390, "https://www.carnivalcorp.com", ["/about"]),
    ("norwegian-cruise", "Norwegian Cruise Line", 391, "https://www.nclhltd.com", ["/about"]),
    ("six-flags", "Six Flags", 392, "https://www.sixflags.com/national/plan-your-visit/about-us", []),
    ("live-nation", "Live Nation Entertainment", 393, "https://www.livenationentertainment.com", ["/about-us"]),
    ("fox", "Fox Corporation", 394, "https://www.foxcorporation.com", ["/about"]),
    ("paramount", "Paramount Global", 395, "https://www.paramount.com/about", []),
    ("news-corp", "News Corp", 396, "https://newscorp.com", ["/about"]),
    ("interpublic", "Interpublic Group", 397, "https://www.interpublic.com", ["/about"]),
    ("omnicom", "Omnicom Group", 398, "https://www.omnicomgroup.com", ["/about"]),
    ("mccormick", "McCormick & Company", 399, "https://www.mccormickcorporation.com", ["/about"]),
    ("conagra", "Conagra Brands", 400, "https://www.conagrabrands.com", ["/about"]),

    # ══════════════════════════════════════════════
    # 401-500
    # ══════════════════════════════════════════════
    ("campbell-soup", "Campbell Soup", 401, "https://www.campbellsoupcompany.com", ["/about-us"]),
    ("smucker", "J.M. Smucker", 402, "https://www.jmsmucker.com", ["/about"]),
    ("hormel", "Hormel Foods", 403, "https://www.hormelfoods.com", ["/about"]),
    ("flowers-foods", "Flowers Foods", 404, "https://www.flowersfoods.com", ["/about-us"]),
    ("post-holdings", "Post Holdings", 405, "https://www.postholdings.com", ["/about-us"]),
    ("treehouse", "TreeHouse Foods", 406, "https://www.treehousefoods.com", ["/who-we-are"]),
    ("pilgrim-pride", "Pilgrim's Pride", 407, "https://www.pilgrims.com", ["/about-us"]),
    ("sanderson-farms", "Sanderson Farms", 408, "https://www.sandersonfarms.com", ["/who-we-are"]),
    ("lamb-weston", "Lamb Weston", 409, "https://www.lambweston.com", ["/about"]),
    ("simply-good", "Simply Good Foods", 410, "https://www.thesimplygoodfoodscompany.com", ["/about-us"]),
    ("church-dwight", "Church & Dwight", 411, "https://www.churchdwight.com", ["/about-us"]),
    ("spectrum-brands", "Spectrum Brands", 412, "https://www.spectrumbrands.com", ["/about-us"]),
    ("energizer", "Energizer Holdings", 413, "https://www.energizerholdings.com", ["/about"]),
    ("scotts-miracle", "Scotts Miracle-Gro", 414, "https://www.scottsmiraclegro.com", ["/about"]),
    ("central-garden", "Central Garden & Pet", 415, "https://www.central.com", ["/about-us"]),
    ("clorox", "Clorox", 416, "https://www.thecloroxcompany.com", ["/who-we-are"]),
    ("henkel", "Henkel (US)", 417, "https://www.henkel.us", ["/company/about-henkel"]),
    ("edgewell", "Edgewell Personal Care", 418, "https://www.edgewell.com", ["/about-edgewell"]),
    ("revlon", "Revlon", 419, "https://www.revloninc.com", ["/about-us"]),
    ("estee-lauder", "Estee Lauder", 420, "https://www.elcompanies.com", ["/who-we-are"]),
    ("coty", "Coty", 421, "https://www.coty.com", ["/about-us"]),
    ("hasbro", "Hasbro", 422, "https://corporate.hasbro.com", ["/about"]),
    ("mattel", "Mattel", 423, "https://corporate.mattel.com", ["/about-us"]),
    ("hanesbrands", "Hanesbrands", 424, "https://www.hanesbrandsinc.com", ["/about-us"]),
    ("pvh", "PVH Corp", 425, "https://www.pvh.com", ["/who-we-are"]),
    ("tapestry", "Tapestry", 426, "https://www.tapestry.com", ["/company"]),
    ("capri", "Capri Holdings", 427, "https://www.capriholdings.com", ["/about"]),
    ("ralph-lauren", "Ralph Lauren", 428, "https://corporate.ralphlauren.com", ["/about"]),
    ("gap", "Gap Inc.", 429, "https://www.gapinc.com", ["/about"]),
    ("vf-corp", "VF Corporation", 430, "https://www.vfc.com", ["/about"]),
    ("levi", "Levi Strauss", 431, "https://www.levistrauss.com", ["/who-we-are"]),
    ("under-armour", "Under Armour", 432, "https://about.underarmour.com", ["/company"]),
    ("skechers", "Skechers", 433, "https://about.skechers.com", ["/who-we-are"]),
    ("deckers", "Deckers Brands", 434, "https://www.deckers.com", ["/about"]),
    ("wolverine", "Wolverine World Wide", 435, "https://www.wolverineworldwide.com", ["/about-us"]),
    ("crocs", "Crocs", 436, "https://www.crocs.com/about.html", []),
    ("bath-body", "Bath & Body Works", 437, "https://www.bbwinc.com", ["/our-company"]),
    ("wayfair", "Wayfair", 438, "https://www.aboutwayfair.com", ["/who-we-are"]),
    ("chewy", "Chewy", 439, "https://www.chewy.com/about", []),
    ("etsy", "Etsy", 440, "https://www.etsy.com/about", []),
    ("ebay", "eBay", 441, "https://www.ebayinc.com", ["/company"]),
    ("carvana", "Carvana", 442, "https://www.carvana.com/about", []),
    ("carmax", "CarMax", 443, "https://www.carmax.com/about-carmax", []),
    ("autonation", "AutoNation", 444, "https://www.autonation.com/about-us", []),
    ("lithia", "Lithia Motors", 445, "https://www.lithia.com", ["/about"]),
    ("group-1", "Group 1 Automotive", 446, "https://www.group1auto.com", ["/about"]),
    ("sonic-auto", "Sonic Automotive", 447, "https://www.sonicautomotive.com", ["/about-us"]),
    ("advance-auto", "Advance Auto Parts", 448, "https://corp.advanceautoparts.com", ["/about-us"]),
    ("oreilly", "O'Reilly Automotive", 449, "https://corporate.oreillyauto.com", ["/about"]),
    ("genuine-parts-auto", "NAPA Auto Parts", 450, "https://www.napaonline.com/about-us", []),
    ("tractor-supply", "Tractor Supply", 451, "https://www.tractorsupply.com/tsc/cms/about-us", []),
    ("five-below", "Five Below", 452, "https://www.fivebelow.com/about-us", []),
    ("burlington", "Burlington Stores", 453, "https://www.burlingtoninvestors.com", ["/about"]),
    ("dollar-tree", "Dollar Tree", 454, "https://www.dollartreeinfo.com", ["/about"]),
    ("ollies", "Ollie's Bargain Outlet", 455, "https://www.ollies.us/about-us", []),
    ("big-lots", "Big Lots", 456, "https://www.biglots.com/page/about-us", []),
    ("williams-sonoma", "Williams-Sonoma", 457, "https://www.williams-sonomainc.com", ["/about"]),
    ("restoration", "RH (Restoration Hardware)", 458, "https://www.restorationhardware.com/content/page.jsp?id=our-story", []),
    ("bed-bath", "Overstock.com", 459, "https://www.overstock.com/about", []),
    ("gamestop", "GameStop", 460, "https://news.gamestop.com", ["/about"]),
    ("dicks-sporting", "Dick's Sporting Goods", 461, "https://www.dickssportinggoods.com/s/about-us", []),
    ("academy-sports", "Academy Sports", 462, "https://www.academy.com/about-us", []),
    ("foot-locker", "Foot Locker", 463, "https://www.footlocker-inc.com", ["/about"]),
    ("ulta", "Ulta Beauty", 464, "https://www.ulta.com/company/about-us", []),
    ("bath-beyond", "Sprouts Farmers Market", 465, "https://about.sprouts.com", []),
    ("grocery-outlet", "Grocery Outlet", 466, "https://www.groceryoutlet.com/about-us", []),
    ("weis-markets", "Weis Markets", 467, "https://www.weismarkets.com/about-weis", []),
    ("casey-general", "Casey's General Stores", 468, "https://www.caseys.com/about", []),
    ("murphy-usa", "Murphy USA", 469, "https://www.murphyusa.com/about", []),
    ("sunoco", "Sunoco LP", 470, "https://www.sunocolp.com", ["/about-us"]),
    ("csx", "CSX Corporation", 471, "https://www.csx.com", ["/about-us"]),
    ("norfolk-southern", "Norfolk Southern", 472, "https://www.norfolksouthern.com", ["/about-us"]),
    ("union-pacific", "Union Pacific", 473, "https://www.up.com", ["/aboutup"]),
    ("bnsf", "BNSF Railway", 474, "https://www.bnsf.com", ["/about-bnsf"]),
    ("jb-hunt", "J.B. Hunt", 475, "https://www.jbhunt.com", ["/our-company"]),
    ("xpo", "XPO", 476, "https://www.xpo.com", ["/about"]),
    ("old-dominion", "Old Dominion Freight", 477, "https://www.odfl.com", ["/about"]),
    ("saia", "Saia Inc.", 478, "https://www.saia.com", ["/about-saia"]),
    ("werner", "Werner Enterprises", 479, "https://www.werner.com", ["/about"]),
    ("landstar", "Landstar System", 480, "https://www.landstar.com", ["/about"]),
    ("fedex", "FedEx", 481, "https://www.fedex.com/en-us/about.html", []),
    ("expeditors", "Expeditors International", 482, "https://www.expeditors.com", ["/about-us"]),
    ("ch-robinson", "C.H. Robinson", 483, "https://www.chrobinson.com", ["/about-us"]),
    ("ryder", "Ryder System", 484, "https://www.ryder.com", ["/about-ryder"]),
    ("penske-truck", "Penske Truck Leasing", 485, "https://www.pensketruckleasing.com/about", []),
    ("avis-budget", "Avis Budget Group", 486, "https://www.avisbudgetgroup.com", ["/about-us"]),
    ("hertz", "Hertz Global", 487, "https://www.hertz.com/rentacar/abouthertz", []),
    ("u-haul", "U-Haul (Amerco)", 488, "https://www.amerco.com", ["/about"]),
    ("lyft", "Lyft", 489, "https://www.lyft.com/about", []),
    ("southwest-gas-2", "Atmos Energy", 490, "https://www.atmosenergy.com", ["/about-us"]),
    ("spire", "Spire Inc.", 491, "https://www.spireenergy.com", ["/about-us"]),
    ("new-jersey-resources", "New Jersey Resources", 492, "https://www.njresources.com", ["/about-us"]),
    ("south-jersey", "South Jersey Industries", 493, "https://www.sjindustries.com", ["/about-us"]),
    ("national-fuel", "National Fuel Gas", 494, "https://www.natfuel.com", ["/about-us"]),
    ("northwest-natural", "Northwest Natural", 495, "https://www.nwnatural.com", ["/about-us"]),
    ("one-gas", "ONE Gas", 496, "https://www.onegas.com", ["/about-us"]),
    ("essential-utilities", "Essential Utilities", 497, "https://www.essential.co", ["/about"]),
    ("american-water", "American Water Works", 498, "https://www.amwater.com", ["/about-us"]),
    ("california-water", "California Water Service", 499, "https://www.calwater.com", ["/about-us"]),
    ("york-water", "York Water Company", 500, "https://www.yorkwater.com", ["/about-us"]),
]
