"""
nti_log.py — The Log

Single source of truth for all NTI events across all surfaces.
Every check, score, rewrite, stamp, override, verify lookup, spend event writes here.

Tables:
    nti_checks      — every check event (the core record)
    nti_overrides   — when a user bypasses a failed check and sends anyway
    nti_stamps      — when a verified stamp is appended to an outbound email
    nti_verify_hits — when someone looks up a stamp at /verify/<request_id>
    nti_spend       — AI call costs per check (for billing and cap enforcement)

All tables share request_id as the join key.
request_id is generated by the calling surface (Outlook add-in, API, etc.)
and passed into every log call — so the full lifecycle of one email can be
reconstructed from a single ID.

Usage:
    from nti_log import log_check, log_override, log_stamp, log_spend, get_check, export_checks

Environment:
    PostgreSQL is required and is accessed through db.db_connect().
"""

import os
import json
import uuid
import time
import logging
from datetime import datetime, timezone
from typing import Optional, List, Dict, Any
import db as database

log = logging.getLogger("nti_log")

# ── CONNECTION ────────────────────────────────────────────────────────────────

def _get_conn():
    """Return a PostgreSQL connection from the canonical database module."""
    return database.db_connect()



def _now() -> str:
    return datetime.now(timezone.utc).isoformat()


# ── SCHEMA INIT ───────────────────────────────────────────────────────────────

def init_log_tables() -> None:
    """Create the canonical NTI and RH request-log tables in PostgreSQL."""
    conn = _get_conn()

    try:
        cur = conn.cursor()

        cur.execute("""
            CREATE TABLE IF NOT EXISTS nti_checks (
                request_id TEXT PRIMARY KEY,
                created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                account_id TEXT,
                user_id TEXT,
                user_email TEXT,
                surface TEXT,
                nti_version TEXT NOT NULL,
                score NUMERIC(5,2),
                nii_raw NUMERIC(5,4),
                band TEXT,
                signals JSONB,
                signal_count INTEGER,
                text_hash TEXT,
                char_count INTEGER,
                word_count INTEGER,
                rewrite_offered BOOLEAN DEFAULT FALSE,
                rewrite_accepted BOOLEAN DEFAULT FALSE,
                latency_ms INTEGER,
                ip TEXT,
                user_agent TEXT,
                metadata JSONB
            )
        """)

        cur.execute("""
            CREATE TABLE IF NOT EXISTS nti_overrides (
                id TEXT PRIMARY KEY,
                created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                request_id TEXT NOT NULL REFERENCES nti_checks(request_id),
                account_id TEXT,
                user_id TEXT,
                user_email TEXT,
                score NUMERIC(5,2),
                signals JSONB,
                override_reason TEXT
            )
        """)

        cur.execute("""
            CREATE TABLE IF NOT EXISTS nti_stamps (
                id TEXT PRIMARY KEY,
                created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                request_id TEXT NOT NULL REFERENCES nti_checks(request_id),
                account_id TEXT,
                user_id TEXT,
                score NUMERIC(5,2),
                stamp_text TEXT,
                recipient_domain TEXT
            )
        """)

        cur.execute("""
            CREATE TABLE IF NOT EXISTS nti_verify_hits (
                id TEXT PRIMARY KEY,
                created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                request_id TEXT NOT NULL,
                lookup_ip TEXT,
                found BOOLEAN
            )
        """)

        cur.execute("""
            CREATE TABLE IF NOT EXISTS nti_spend (
                id TEXT PRIMARY KEY,
                created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                request_id TEXT,
                account_id TEXT,
                model TEXT,
                call_type TEXT,
                input_tokens INTEGER,
                output_tokens INTEGER,
                cost_usd NUMERIC(10,6),
                markup_usd NUMERIC(10,6)
            )
        """)

        cur.execute("""
            CREATE TABLE IF NOT EXISTS rh_api_requests (
                id BIGSERIAL PRIMARY KEY,
                request_id TEXT NOT NULL,
                endpoint TEXT NOT NULL,
                status_code INTEGER NOT NULL,
                latency_ms NUMERIC(10,2),
                api_key_id TEXT,
                created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
            )
        """)

        for statement in (
            "CREATE INDEX IF NOT EXISTS idx_checks_account "
            "ON nti_checks(account_id)",

            "CREATE INDEX IF NOT EXISTS idx_checks_user "
            "ON nti_checks(user_id)",

            "CREATE INDEX IF NOT EXISTS idx_checks_created "
            "ON nti_checks(created_at)",

            "CREATE INDEX IF NOT EXISTS idx_overrides_request "
            "ON nti_overrides(request_id)",

            "CREATE INDEX IF NOT EXISTS idx_stamps_request "
            "ON nti_stamps(request_id)",

            "CREATE INDEX IF NOT EXISTS idx_spend_account "
            "ON nti_spend(account_id)",

            "CREATE INDEX IF NOT EXISTS idx_rh_api_requests_created "
            "ON rh_api_requests(created_at)",

            "CREATE INDEX IF NOT EXISTS idx_rh_api_requests_key "
            "ON rh_api_requests(api_key_id)",
        ):
            cur.execute(statement)

        conn.commit()
        log.info("nti_log: PostgreSQL tables initialized")

    except Exception:
        conn.rollback()
        raise

    finally:
        conn.close()



# ── WRITE: CHECK ──────────────────────────────────────────────────────────────

def log_check(
    request_id: str,
    nti_version: str,
    score: float,
    nii_raw: float,
    signals: List[str],
    char_count: int,
    word_count: int,
    text_hash: str,
    latency_ms: int,
    surface: str = "api",
    account_id: Optional[str] = None,
    user_id: Optional[str] = None,
    user_email: Optional[str] = None,
    rewrite_offered: bool = False,
    rewrite_accepted: bool = False,
    ip: Optional[str] = None,
    user_agent: Optional[str] = None,
    metadata: Optional[Dict] = None,
) -> bool:
    """Write an NTI check event to PostgreSQL."""
    band = _score_to_band(score)
    conn = None

    try:
        conn = _get_conn()
        cur = conn.cursor()

        cur.execute("""
            INSERT INTO nti_checks (
                request_id,
                account_id,
                user_id,
                user_email,
                surface,
                nti_version,
                score,
                nii_raw,
                band,
                signals,
                signal_count,
                text_hash,
                char_count,
                word_count,
                rewrite_offered,
                rewrite_accepted,
                latency_ms,
                ip,
                user_agent,
                metadata
            )
            VALUES (
                %s, %s, %s, %s, %s,
                %s, %s, %s, %s, %s::jsonb,
                %s, %s, %s, %s, %s,
                %s, %s, %s, %s, %s::jsonb
            )
            ON CONFLICT (request_id) DO NOTHING
        """, (
            request_id,
            account_id,
            user_id,
            user_email,
            surface,
            nti_version,
            round(score, 2),
            round(nii_raw, 4),
            band,
            json.dumps(signals),
            len(signals),
            text_hash,
            char_count,
            word_count,
            rewrite_offered,
            rewrite_accepted,
            latency_ms,
            ip,
            user_agent,
            json.dumps(metadata or {}),
        ))

        conn.commit()
        return True

    except Exception as error:
        if conn is not None:
            conn.rollback()

        log.error(f"log_check failed: {error}")
        return False

    finally:
        if conn is not None:
            conn.close()



# ── WRITE: REWRITE ACCEPTED ───────────────────────────────────────────────────

def log_rewrite_accepted(request_id: str) -> bool:
    """Mark an NTI rewrite as accepted."""
    conn = None

    try:
        conn = _get_conn()
        cur = conn.cursor()

        cur.execute(
            """
            UPDATE nti_checks
            SET rewrite_accepted = TRUE
            WHERE request_id = %s
            """,
            (request_id,),
        )

        conn.commit()
        return True

    except Exception as error:
        if conn is not None:
            conn.rollback()

        log.error(f"log_rewrite_accepted failed: {error}")
        return False

    finally:
        if conn is not None:
            conn.close()



# ── WRITE: OVERRIDE ───────────────────────────────────────────────────────────

def log_override(
    request_id: str,
    score: float,
    signals: List[str],
    account_id: Optional[str] = None,
    user_id: Optional[str] = None,
    user_email: Optional[str] = None,
    override_reason: Optional[str] = None,
) -> bool:
    """Record a user override of an NTI result."""
    conn = None

    try:
        conn = _get_conn()
        cur = conn.cursor()

        cur.execute("""
            INSERT INTO nti_overrides (
                id,
                request_id,
                account_id,
                user_id,
                user_email,
                score,
                signals,
                override_reason
            )
            VALUES (%s, %s, %s, %s, %s, %s, %s::jsonb, %s)
        """, (
            str(uuid.uuid4()),
            request_id,
            account_id,
            user_id,
            user_email,
            round(score, 2),
            json.dumps(signals),
            override_reason,
        ))

        conn.commit()
        return True

    except Exception as error:
        if conn is not None:
            conn.rollback()

        log.error(f"log_override failed: {error}")
        return False

    finally:
        if conn is not None:
            conn.close()



# ── WRITE: STAMP ──────────────────────────────────────────────────────────────

def log_stamp(
    request_id: str,
    score: float,
    stamp_text: str,
    account_id: Optional[str] = None,
    user_id: Optional[str] = None,
    recipient_domain: Optional[str] = None,
) -> bool:
    """Record an NTI verification stamp."""
    conn = None

    try:
        conn = _get_conn()
        cur = conn.cursor()

        cur.execute("""
            INSERT INTO nti_stamps (
                id,
                request_id,
                account_id,
                user_id,
                score,
                stamp_text,
                recipient_domain
            )
            VALUES (%s, %s, %s, %s, %s, %s, %s)
        """, (
            str(uuid.uuid4()),
            request_id,
            account_id,
            user_id,
            round(score, 2),
            stamp_text,
            recipient_domain,
        ))

        conn.commit()
        return True

    except Exception as error:
        if conn is not None:
            conn.rollback()

        log.error(f"log_stamp failed: {error}")
        return False

    finally:
        if conn is not None:
            conn.close()



# ── WRITE: SPEND ──────────────────────────────────────────────────────────────

def log_spend(
    model: str,
    call_type: str,
    input_tokens: int,
    output_tokens: int,
    cost_usd: float,
    markup_pct: float = 0.15,
    request_id: Optional[str] = None,
    account_id: Optional[str] = None,
) -> bool:
    """Record model usage and marked-up spend."""
    markup_usd = round(cost_usd * markup_pct, 6)
    conn = None

    try:
        conn = _get_conn()
        cur = conn.cursor()

        cur.execute("""
            INSERT INTO nti_spend (
                id,
                request_id,
                account_id,
                model,
                call_type,
                input_tokens,
                output_tokens,
                cost_usd,
                markup_usd
            )
            VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s)
        """, (
            str(uuid.uuid4()),
            request_id,
            account_id,
            model,
            call_type,
            input_tokens,
            output_tokens,
            round(cost_usd, 6),
            markup_usd,
        ))

        conn.commit()
        return True

    except Exception as error:
        if conn is not None:
            conn.rollback()

        log.error(f"log_spend failed: {error}")
        return False

    finally:
        if conn is not None:
            conn.close()



# ── READ: VERIFY ──────────────────────────────────────────────────────────────

def get_check(
    request_id: str,
    lookup_ip: Optional[str] = None,
) -> Optional[Dict]:
    """
    Return the public verification record and log the lookup attempt.
    """
    conn = None

    try:
        conn = _get_conn()
        cur = conn.cursor()

        cur.execute("""
            SELECT
                request_id,
                created_at,
                nti_version,
                score,
                band,
                signals,
                signal_count
            FROM nti_checks
            WHERE request_id = %s
        """, (request_id,))

        row = cur.fetchone()
        found = row is not None
        result = None

        if found:
            raw_signals = row[5]

            if isinstance(raw_signals, str):
                parsed_signals = json.loads(raw_signals)
            else:
                parsed_signals = raw_signals or []

            result = {
                "request_id": row[0],
                "checked_at": row[1],
                "nti_version": row[2],
                "score": (
                    float(row[3])
                    if row[3] is not None
                    else None
                ),
                "band": row[4],
                "signals": parsed_signals,
                "signal_count": row[6],
                "verified": True,
            }

        cur.execute("""
            INSERT INTO nti_verify_hits (
                id,
                request_id,
                lookup_ip,
                found
            )
            VALUES (%s, %s, %s, %s)
        """, (
            str(uuid.uuid4()),
            request_id,
            lookup_ip,
            found,
        ))

        conn.commit()
        return result

    except Exception as error:
        if conn is not None:
            conn.rollback()

        log.error(f"get_check failed: {error}")
        return None

    finally:
        if conn is not None:
            conn.close()



# ── READ: REPORTING ───────────────────────────────────────────────────────────

def get_account_stats(
    account_id: str,
    days: int = 30,
) -> Dict[str, Any]:
    """Return PostgreSQL-backed NTI account statistics."""
    conn = None

    try:
        period_days = max(
            1,
            min(int(days), 3650),
        )

        conn = _get_conn()
        cur = conn.cursor()

        cur.execute("""
            SELECT
                COUNT(*) AS total_checks,
                ROUND(AVG(score)::numeric, 1) AS avg_score,
                COUNT(*) FILTER (
                    WHERE band = 'SOLID'
                ) AS solid_count,
                COUNT(*) FILTER (
                    WHERE band = 'REVIEW'
                ) AS review_count,
                COUNT(*) FILTER (
                    WHERE band = 'HIGH_RISK'
                ) AS high_risk_count,
                COUNT(*) FILTER (
                    WHERE rewrite_accepted = TRUE
                ) AS rewrites_accepted,
                COUNT(*) FILTER (
                    WHERE rewrite_offered = TRUE
                ) AS rewrites_offered
            FROM nti_checks
            WHERE account_id = %s
              AND created_at >= (
                  NOW() - (%s * INTERVAL '1 day')
              )
        """, (
            account_id,
            period_days,
        ))

        stats = cur.fetchone()

        cur.execute("""
            SELECT COUNT(*)
            FROM nti_overrides
            WHERE account_id = %s
              AND created_at >= (
                  NOW() - (%s * INTERVAL '1 day')
              )
        """, (
            account_id,
            period_days,
        ))

        override_count = cur.fetchone()[0]

        cur.execute("""
            SELECT ROUND(
                SUM(cost_usd + markup_usd)::numeric,
                4
            )
            FROM nti_spend
            WHERE account_id = %s
              AND created_at >= (
                  NOW() - (%s * INTERVAL '1 day')
              )
        """, (
            account_id,
            period_days,
        ))

        spend = cur.fetchone()[0] or 0.0

        rewrite_rate = 0.0

        if stats[6] and stats[6] > 0:
            rewrite_rate = round(
                (stats[5] or 0)
                / stats[6]
                * 100,
                1,
            )

        return {
            "account_id": account_id,
            "period_days": period_days,
            "total_checks": stats[0] or 0,
            "avg_score": (
                float(stats[1])
                if stats[1] is not None
                else 0.0
            ),
            "band_distribution": {
                "solid": stats[2] or 0,
                "review": stats[3] or 0,
                "high_risk": stats[4] or 0,
            },
            "override_count": override_count or 0,
            "rewrite_acceptance_rate_pct": rewrite_rate,
            "spend_usd": float(spend),
        }

    except Exception as error:
        log.error(f"get_account_stats failed: {error}")
        return {}

    finally:
        if conn is not None:
            conn.close()



def export_checks_csv(
    account_id: str,
    days: int = 30,
) -> List[Dict]:
    """Return PostgreSQL NTI check records for CSV export."""
    conn = None

    try:
        period_days = max(
            1,
            min(int(days), 3650),
        )

        conn = _get_conn()
        cur = conn.cursor()

        cur.execute("""
            SELECT
                request_id,
                created_at,
                user_email,
                surface,
                score,
                band,
                signal_count,
                signals,
                rewrite_offered,
                rewrite_accepted,
                latency_ms
            FROM nti_checks
            WHERE account_id = %s
              AND created_at >= (
                  NOW() - (%s * INTERVAL '1 day')
              )
            ORDER BY created_at DESC
        """, (
            account_id,
            period_days,
        ))

        columns = [
            description[0]
            for description in cur.description
        ]

        return [
            dict(zip(columns, row))
            for row in cur.fetchall()
        ]

    except Exception as error:
        log.error(f"export_checks_csv failed: {error}")
        return []

    finally:
        if conn is not None:
            conn.close()



# ── HELPERS ───────────────────────────────────────────────────────────────────

def _score_to_band(score: float) -> str:
    if score >= 80:
        return "SOLID"
    elif score >= 60:
        return "REVIEW"
    return "HIGH_RISK"


def make_request_id() -> str:
    """Generate a request ID. Surfaces can use this or supply their own."""
    return str(uuid.uuid4())


def hash_text(text: str) -> str:
    """SHA256 of input text. Stored in log — never the text itself."""
    import hashlib
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def log_request(
    request_id: str,
    endpoint: str,
    status_code: int,
    latency_ms: float,
    api_key_id: str = None,
) -> None:
    """Record an RH Toolkit API request in PostgreSQL."""
    conn = None

    try:
        conn = _get_conn()
        cur = conn.cursor()

        cur.execute("""
            INSERT INTO rh_api_requests (
                request_id,
                endpoint,
                status_code,
                latency_ms,
                api_key_id
            )
            VALUES (%s, %s, %s, %s, %s)
        """, (
            request_id,
            endpoint,
            status_code,
            round(latency_ms, 2),
            api_key_id,
        ))

        conn.commit()

    except Exception as error:
        if conn is not None:
            conn.rollback()

        log.error(f"log_request failed: {error}")

    finally:
        if conn is not None:
            conn.close()





