"""
nti_log.py — The Log

Single source of truth for all NTI events across all surfaces.
Every check, score, rewrite, stamp, override, verify lookup, spend event writes here.

Tables:
    nti_checks      — every check event (the core record)
    nti_overrides   — when a user bypasses a failed check and sends anyway
    nti_stamps      — when a verified stamp is appended to an outbound email
    nti_verify_hits — when someone looks up a stamp at /verify/<request_id>
    nti_spend       — AI call costs per check (for billing and cap enforcement)

All tables share request_id as the join key.
request_id is generated by the calling surface (Outlook add-in, API, etc.)
and passed into every log call — so the full lifecycle of one email can be
reconstructed from a single ID.

Usage:
    from nti_log import log_check, log_override, log_stamp, log_spend, get_check, export_checks

Environment:
    DATABASE_URL — PostgreSQL connection string (required in production)
    Falls back to SQLite at /tmp/nti_log.db for local dev only.
"""

import os
import json
import uuid
import time
import logging
from datetime import datetime, timezone
from typing import Optional, List, Dict, Any

log = logging.getLogger("nti_log")

# ── CONNECTION ────────────────────────────────────────────────────────────────

DATABASE_URL = os.getenv("DATABASE_URL", "")

def _get_conn():
    """Return a DB connection. Postgres in production, SQLite for local dev."""
    if DATABASE_URL:
        try:
            import psycopg2
            import psycopg2.extras
            conn = psycopg2.connect(DATABASE_URL)
            return conn, "postgres"
        except ImportError:
            raise RuntimeError("psycopg2 not installed. Add psycopg2-binary to requirements.txt")
    else:
        import sqlite3
        conn = sqlite3.connect("/tmp/nti_log.db")
        conn.row_factory = sqlite3.Row
        return conn, "sqlite"


def _now() -> str:
    return datetime.now(timezone.utc).isoformat()


# ── SCHEMA INIT ───────────────────────────────────────────────────────────────

def init_log_tables() -> None:
    """Create all log tables if they don't exist. Safe to call on every startup."""
    conn, driver = _get_conn()
    cur = conn.cursor()

    if driver == "postgres":
        cur.execute("""
            CREATE TABLE IF NOT EXISTS nti_checks (
                request_id      TEXT PRIMARY KEY,
                created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                account_id      TEXT,
                user_id         TEXT,
                user_email      TEXT,
                surface         TEXT,           -- 'outlook' | 'gmail' | 'api' | 'slack' | 'teams' etc
                nti_version     TEXT NOT NULL,
                score           NUMERIC(5,2),   -- 0.00 to 100.00
                nii_raw         NUMERIC(5,4),   -- 0.0000 to 1.0000 (engine native)
                band            TEXT,           -- 'SOLID' | 'REVIEW' | 'HIGH_RISK'
                signals         JSONB,          -- array of signal IDs fired
                signal_count    INTEGER,
                text_hash       TEXT,           -- SHA256 of input text (not the text itself)
                char_count      INTEGER,
                word_count      INTEGER,
                rewrite_offered BOOLEAN DEFAULT FALSE,
                rewrite_accepted BOOLEAN DEFAULT FALSE,
                latency_ms      INTEGER,
                ip              TEXT,
                user_agent      TEXT,
                metadata        JSONB           -- catch-all for surface-specific data
            )
        """)

        cur.execute("""
            CREATE TABLE IF NOT EXISTS nti_overrides (
                id              TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,
                created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                request_id      TEXT NOT NULL REFERENCES nti_checks(request_id),
                account_id      TEXT,
                user_id         TEXT,
                user_email      TEXT,
                score           NUMERIC(5,2),
                signals         JSONB,
                override_reason TEXT            -- optional: user-provided reason
            )
        """)

        cur.execute("""
            CREATE TABLE IF NOT EXISTS nti_stamps (
                id              TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,
                created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                request_id      TEXT NOT NULL REFERENCES nti_checks(request_id),
                account_id      TEXT,
                user_id         TEXT,
                score           NUMERIC(5,2),
                stamp_text      TEXT,           -- the actual stamp appended
                recipient_domain TEXT           -- domain of To: address (no PII)
            )
        """)

        cur.execute("""
            CREATE TABLE IF NOT EXISTS nti_verify_hits (
                id              TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,
                created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                request_id      TEXT NOT NULL,
                lookup_ip       TEXT,
                found           BOOLEAN
            )
        """)

        cur.execute("""
            CREATE TABLE IF NOT EXISTS nti_spend (
                id              TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,
                created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                request_id      TEXT,
                account_id      TEXT,
                model           TEXT,           -- 'claude' | 'openai'
                call_type       TEXT,           -- 'ungoverned' | 'governed' | 'draft_reply'
                input_tokens    INTEGER,
                output_tokens   INTEGER,
                cost_usd        NUMERIC(10,6),
                markup_usd      NUMERIC(10,6)
            )
        """)

        # Indexes for common query patterns
        cur.execute("CREATE INDEX IF NOT EXISTS idx_checks_account ON nti_checks(account_id)")
        cur.execute("CREATE INDEX IF NOT EXISTS idx_checks_user ON nti_checks(user_id)")
        cur.execute("CREATE INDEX IF NOT EXISTS idx_checks_created ON nti_checks(created_at)")
        cur.execute("CREATE INDEX IF NOT EXISTS idx_overrides_request ON nti_overrides(request_id)")
        cur.execute("CREATE INDEX IF NOT EXISTS idx_stamps_request ON nti_stamps(request_id)")
        cur.execute("CREATE INDEX IF NOT EXISTS idx_spend_account ON nti_spend(account_id)")

    else:
        # SQLite fallback for local dev
        cur.executescript("""
            CREATE TABLE IF NOT EXISTS nti_checks (
                request_id TEXT PRIMARY KEY,
                created_at TEXT NOT NULL,
                account_id TEXT, user_id TEXT, user_email TEXT, surface TEXT,
                nti_version TEXT NOT NULL, score REAL, nii_raw REAL, band TEXT,
                signals TEXT, signal_count INTEGER, text_hash TEXT,
                char_count INTEGER, word_count INTEGER,
                rewrite_offered INTEGER DEFAULT 0, rewrite_accepted INTEGER DEFAULT 0,
                latency_ms INTEGER, ip TEXT, user_agent TEXT, metadata TEXT
            );
            CREATE TABLE IF NOT EXISTS nti_overrides (
                id TEXT PRIMARY KEY, created_at TEXT NOT NULL,
                request_id TEXT NOT NULL, account_id TEXT, user_id TEXT,
                user_email TEXT, score REAL, signals TEXT, override_reason TEXT
            );
            CREATE TABLE IF NOT EXISTS nti_stamps (
                id TEXT PRIMARY KEY, created_at TEXT NOT NULL,
                request_id TEXT NOT NULL, account_id TEXT, user_id TEXT,
                score REAL, stamp_text TEXT, recipient_domain TEXT
            );
            CREATE TABLE IF NOT EXISTS nti_verify_hits (
                id TEXT PRIMARY KEY, created_at TEXT NOT NULL,
                request_id TEXT NOT NULL, lookup_ip TEXT, found INTEGER
            );
            CREATE TABLE IF NOT EXISTS nti_spend (
                id TEXT PRIMARY KEY, created_at TEXT NOT NULL,
                request_id TEXT, account_id TEXT, model TEXT, call_type TEXT,
                input_tokens INTEGER, output_tokens INTEGER,
                cost_usd REAL, markup_usd REAL
            );
        """)

    conn.commit()
    cur.close()
    conn.close()
    log.info("nti_log: tables initialized")


# ── WRITE: CHECK ──────────────────────────────────────────────────────────────

def log_check(
    request_id: str,
    nti_version: str,
    score: float,                   # 0-100 scale
    nii_raw: float,                 # 0.0-1.0 engine native
    signals: List[str],
    char_count: int,
    word_count: int,
    text_hash: str,
    latency_ms: int,
    surface: str = "api",
    account_id: Optional[str] = None,
    user_id: Optional[str] = None,
    user_email: Optional[str] = None,
    rewrite_offered: bool = False,
    rewrite_accepted: bool = False,
    ip: Optional[str] = None,
    user_agent: Optional[str] = None,
    metadata: Optional[Dict] = None,
) -> bool:
    """Write a check event. Returns True on success."""
    band = _score_to_band(score)
    try:
        conn, driver = _get_conn()
        cur = conn.cursor()
        if driver == "postgres":
            cur.execute("""
                INSERT INTO nti_checks
                (request_id, account_id, user_id, user_email, surface,
                 nti_version, score, nii_raw, band, signals, signal_count,
                 text_hash, char_count, word_count, rewrite_offered, rewrite_accepted,
                 latency_ms, ip, user_agent, metadata)
                VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)
                ON CONFLICT (request_id) DO NOTHING
            """, (
                request_id, account_id, user_id, user_email, surface,
                nti_version, round(score, 2), round(nii_raw, 4), band,
                json.dumps(signals), len(signals),
                text_hash, char_count, word_count,
                rewrite_offered, rewrite_accepted,
                latency_ms, ip, user_agent,
                json.dumps(metadata or {})
            ))
        else:
            cur.execute("""
                INSERT OR IGNORE INTO nti_checks
                (request_id, created_at, account_id, user_id, user_email, surface,
                 nti_version, score, nii_raw, band, signals, signal_count,
                 text_hash, char_count, word_count, rewrite_offered, rewrite_accepted,
                 latency_ms, ip, user_agent, metadata)
                VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)
            """, (
                request_id, _now(), account_id, user_id, user_email, surface,
                nti_version, round(score, 2), round(nii_raw, 4), band,
                json.dumps(signals), len(signals),
                text_hash, char_count, word_count,
                int(rewrite_offered), int(rewrite_accepted),
                latency_ms, ip, user_agent,
                json.dumps(metadata or {})
            ))
        conn.commit()
        cur.close()
        conn.close()
        return True
    except Exception as e:
        log.error(f"log_check failed: {e}")
        return False


# ── WRITE: REWRITE ACCEPTED ───────────────────────────────────────────────────

def log_rewrite_accepted(request_id: str) -> bool:
    """Mark a check record as having had its rewrite accepted by the user."""
    try:
        conn, driver = _get_conn()
        cur = conn.cursor()
        if driver == "postgres":
            cur.execute(
                "UPDATE nti_checks SET rewrite_accepted = TRUE WHERE request_id = %s",
                (request_id,)
            )
        else:
            cur.execute(
                "UPDATE nti_checks SET rewrite_accepted = 1 WHERE request_id = ?",
                (request_id,)
            )
        conn.commit()
        cur.close()
        conn.close()
        return True
    except Exception as e:
        log.error(f"log_rewrite_accepted failed: {e}")
        return False


# ── WRITE: OVERRIDE ───────────────────────────────────────────────────────────

def log_override(
    request_id: str,
    score: float,
    signals: List[str],
    account_id: Optional[str] = None,
    user_id: Optional[str] = None,
    user_email: Optional[str] = None,
    override_reason: Optional[str] = None,
) -> bool:
    """Log when a user bypasses a failed check and sends anyway."""
    try:
        conn, driver = _get_conn()
        cur = conn.cursor()
        oid = str(uuid.uuid4())
        if driver == "postgres":
            cur.execute("""
                INSERT INTO nti_overrides
                (id, request_id, account_id, user_id, user_email, score, signals, override_reason)
                VALUES (%s,%s,%s,%s,%s,%s,%s,%s)
            """, (oid, request_id, account_id, user_id, user_email,
                  round(score, 2), json.dumps(signals), override_reason))
        else:
            cur.execute("""
                INSERT INTO nti_overrides
                (id, created_at, request_id, account_id, user_id, user_email, score, signals, override_reason)
                VALUES (?,?,?,?,?,?,?,?,?)
            """, (oid, _now(), request_id, account_id, user_id, user_email,
                  round(score, 2), json.dumps(signals), override_reason))
        conn.commit()
        cur.close()
        conn.close()
        return True
    except Exception as e:
        log.error(f"log_override failed: {e}")
        return False


# ── WRITE: STAMP ──────────────────────────────────────────────────────────────

def log_stamp(
    request_id: str,
    score: float,
    stamp_text: str,
    account_id: Optional[str] = None,
    user_id: Optional[str] = None,
    recipient_domain: Optional[str] = None,
) -> bool:
    """Log when a verified stamp is appended to an outbound email."""
    try:
        conn, driver = _get_conn()
        cur = conn.cursor()
        sid = str(uuid.uuid4())
        if driver == "postgres":
            cur.execute("""
                INSERT INTO nti_stamps
                (id, request_id, account_id, user_id, score, stamp_text, recipient_domain)
                VALUES (%s,%s,%s,%s,%s,%s,%s)
            """, (sid, request_id, account_id, user_id,
                  round(score, 2), stamp_text, recipient_domain))
        else:
            cur.execute("""
                INSERT INTO nti_stamps
                (id, created_at, request_id, account_id, user_id, score, stamp_text, recipient_domain)
                VALUES (?,?,?,?,?,?,?,?)
            """, (sid, _now(), request_id, account_id, user_id,
                  round(score, 2), stamp_text, recipient_domain))
        conn.commit()
        cur.close()
        conn.close()
        return True
    except Exception as e:
        log.error(f"log_stamp failed: {e}")
        return False


# ── WRITE: SPEND ──────────────────────────────────────────────────────────────

def log_spend(
    model: str,
    call_type: str,
    input_tokens: int,
    output_tokens: int,
    cost_usd: float,
    markup_pct: float = 0.15,
    request_id: Optional[str] = None,
    account_id: Optional[str] = None,
) -> bool:
    """Log AI call cost. markup_pct applied on top of cost_usd."""
    markup_usd = round(cost_usd * markup_pct, 6)
    try:
        conn, driver = _get_conn()
        cur = conn.cursor()
        sid = str(uuid.uuid4())
        if driver == "postgres":
            cur.execute("""
                INSERT INTO nti_spend
                (id, request_id, account_id, model, call_type,
                 input_tokens, output_tokens, cost_usd, markup_usd)
                VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s)
            """, (sid, request_id, account_id, model, call_type,
                  input_tokens, output_tokens, round(cost_usd, 6), markup_usd))
        else:
            cur.execute("""
                INSERT INTO nti_spend
                (id, created_at, request_id, account_id, model, call_type,
                 input_tokens, output_tokens, cost_usd, markup_usd)
                VALUES (?,?,?,?,?,?,?,?,?,?)
            """, (sid, _now(), request_id, account_id, model, call_type,
                  input_tokens, output_tokens, round(cost_usd, 6), markup_usd))
        conn.commit()
        cur.close()
        conn.close()
        return True
    except Exception as e:
        log.error(f"log_spend failed: {e}")
        return False


# ── READ: VERIFY ──────────────────────────────────────────────────────────────

def get_check(request_id: str, lookup_ip: Optional[str] = None) -> Optional[Dict]:
    """
    Public verify lookup. Returns the minimum needed for /verify/<request_id>.
    Logs the lookup hit regardless of found/not found.
    """
    try:
        conn, driver = _get_conn()
        cur = conn.cursor()
        if driver == "postgres":
            cur.execute("""
                SELECT request_id, created_at, nti_version, score, band, signals, signal_count
                FROM nti_checks WHERE request_id = %s
            """, (request_id,))
            row = cur.fetchone()
        else:
            cur.execute("""
                SELECT request_id, created_at, nti_version, score, band, signals, signal_count
                FROM nti_checks WHERE request_id = ?
            """, (request_id,))
            row = cur.fetchone()

        found = row is not None
        result = None

        if found:
            result = {
                "request_id": row[0],
                "checked_at": row[1],
                "nti_version": row[2],
                "score": float(row[3]) if row[3] is not None else None,
                "band": row[4],
                "signals": json.loads(row[5]) if row[5] else [],
                "signal_count": row[6],
                "verified": True,
            }

        # Log the lookup
        vid = str(uuid.uuid4())
        if driver == "postgres":
            cur.execute("""
                INSERT INTO nti_verify_hits (id, request_id, lookup_ip, found)
                VALUES (%s,%s,%s,%s)
            """, (vid, request_id, lookup_ip, found))
        else:
            cur.execute("""
                INSERT INTO nti_verify_hits (id, created_at, request_id, lookup_ip, found)
                VALUES (?,?,?,?,?)
            """, (vid, _now(), request_id, lookup_ip, int(found)))

        conn.commit()
        cur.close()
        conn.close()
        return result

    except Exception as e:
        log.error(f"get_check failed: {e}")
        return None


# ── READ: REPORTING ───────────────────────────────────────────────────────────

def get_account_stats(
    account_id: str,
    days: int = 30,
) -> Dict[str, Any]:
    """
    Aggregate stats for the reporting dashboard.
    Returns: check count, avg score, band distribution, top signals,
             override count, rewrite acceptance rate, spend total.
    """
    try:
        conn, driver = _get_conn()
        cur = conn.cursor()

        if driver == "postgres":
            cur.execute("""
                SELECT
                    COUNT(*)                                        AS total_checks,
                    ROUND(AVG(score)::numeric, 1)                  AS avg_score,
                    COUNT(*) FILTER (WHERE band = 'SOLID')         AS solid_count,
                    COUNT(*) FILTER (WHERE band = 'REVIEW')        AS review_count,
                    COUNT(*) FILTER (WHERE band = 'HIGH_RISK')     AS high_risk_count,
                    COUNT(*) FILTER (WHERE rewrite_accepted = TRUE) AS rewrites_accepted,
                    COUNT(*) FILTER (WHERE rewrite_offered = TRUE)  AS rewrites_offered
                FROM nti_checks
                WHERE account_id = %s
                  AND created_at >= NOW() - INTERVAL '%s days'
            """, (account_id, days))
            stats = cur.fetchone()

            cur.execute("""
                SELECT COUNT(*) FROM nti_overrides
                WHERE account_id = %s
                  AND created_at >= NOW() - INTERVAL '%s days'
            """, (account_id, days))
            override_count = cur.fetchone()[0]

            cur.execute("""
                SELECT ROUND(SUM(cost_usd + markup_usd)::numeric, 4)
                FROM nti_spend
                WHERE account_id = %s
                  AND created_at >= NOW() - INTERVAL '%s days'
            """, (account_id, days))
            spend = cur.fetchone()[0] or 0.0

        else:
            cur.execute("""
                SELECT
                    COUNT(*) AS total_checks,
                    ROUND(AVG(score), 1) AS avg_score,
                    SUM(CASE WHEN band='SOLID' THEN 1 ELSE 0 END),
                    SUM(CASE WHEN band='REVIEW' THEN 1 ELSE 0 END),
                    SUM(CASE WHEN band='HIGH_RISK' THEN 1 ELSE 0 END),
                    SUM(CASE WHEN rewrite_accepted=1 THEN 1 ELSE 0 END),
                    SUM(CASE WHEN rewrite_offered=1 THEN 1 ELSE 0 END)
                FROM nti_checks
                WHERE account_id = ?
                  AND created_at >= datetime('now', ? || ' days')
            """, (account_id, f"-{days}"))
            stats = cur.fetchone()

            cur.execute("""
                SELECT COUNT(*) FROM nti_overrides
                WHERE account_id = ?
                  AND created_at >= datetime('now', ? || ' days')
            """, (account_id, f"-{days}"))
            override_count = cur.fetchone()[0]
            spend = 0.0

        rewrite_rate = 0.0
        if stats[6] and stats[6] > 0:
            rewrite_rate = round((stats[5] or 0) / stats[6] * 100, 1)

        cur.close()
        conn.close()

        return {
            "account_id": account_id,
            "period_days": days,
            "total_checks": stats[0] or 0,
            "avg_score": float(stats[1]) if stats[1] else 0.0,
            "band_distribution": {
                "solid": stats[2] or 0,
                "review": stats[3] or 0,
                "high_risk": stats[4] or 0,
            },
            "override_count": override_count or 0,
            "rewrite_acceptance_rate_pct": rewrite_rate,
            "spend_usd": float(spend),
        }

    except Exception as e:
        log.error(f"get_account_stats failed: {e}")
        return {}


def export_checks_csv(
    account_id: str,
    days: int = 30,
) -> List[Dict]:
    """Return check records as list of dicts for CSV export."""
    try:
        conn, driver = _get_conn()
        cur = conn.cursor()
        if driver == "postgres":
            cur.execute("""
                SELECT request_id, created_at, user_email, surface,
                       score, band, signal_count, signals,
                       rewrite_offered, rewrite_accepted, latency_ms
                FROM nti_checks
                WHERE account_id = %s
                  AND created_at >= NOW() - INTERVAL '%s days'
                ORDER BY created_at DESC
            """, (account_id, days))
            cols = [d[0] for d in cur.description]
            rows = [dict(zip(cols, r)) for r in cur.fetchall()]
        else:
            cur.execute("""
                SELECT request_id, created_at, user_email, surface,
                       score, band, signal_count, signals,
                       rewrite_offered, rewrite_accepted, latency_ms
                FROM nti_checks
                WHERE account_id = ?
                  AND created_at >= datetime('now', ? || ' days')
                ORDER BY created_at DESC
            """, (account_id, f"-{days}"))
            cols = [d[0] for d in cur.description]
            rows = [dict(zip(cols, r)) for r in cur.fetchall()]

        cur.close()
        conn.close()
        return rows
    except Exception as e:
        log.error(f"export_checks_csv failed: {e}")
        return []


# ── HELPERS ───────────────────────────────────────────────────────────────────

def _score_to_band(score: float) -> str:
    if score >= 80:
        return "SOLID"
    elif score >= 60:
        return "REVIEW"
    return "HIGH_RISK"


def make_request_id() -> str:
    """Generate a request ID. Surfaces can use this or supply their own."""
    return str(uuid.uuid4())


def hash_text(text: str) -> str:
    """SHA256 of input text. Stored in log — never the text itself."""
    import hashlib
    return hashlib.sha256(text.encode("utf-8")).hexdigest()
