"""Central semantic tag vocabulary and groupings."""

from __future__ import annotations

AFFILIATION = "AFFILIATION"
SUPPORT = "SUPPORT"
CONCERN = "CONCERN"
DURATION = "DURATION"
ASSUMPTION = "ASSUMPTION"
MESSAGE_ACTION = "MESSAGE_ACTION"
EXPECTATION = "EXPECTATION"
POSITIVE_EVALUATION = "POSITIVE_EVALUATION"
SELF_STATE = "SELF_STATE"
JUDGMENT = "JUDGMENT"
DISSATISFACTION = "DISSATISFACTION"
FUTURE_EXPECTATION = "FUTURE_EXPECTATION"
CONDITION_PROMPT = "CONDITION_PROMPT"
SELF_ACCOUNTABILITY_PROMPT = "SELF_ACCOUNTABILITY_PROMPT"
INVITATION = "INVITATION"
ACTION_REPORT = "ACTION_REPORT"
ANTICIPATED_REACTION = "ANTICIPATED_REACTION"
CARE_FRAME = "CARE_FRAME"
DELAY_JUSTIFICATION = "DELAY_JUSTIFICATION"
SCARCITY = "SCARCITY"
UNCERTAINTY = "UNCERTAINTY"
FUTURE_CONTACT = "FUTURE_CONTACT"
UNCLASSIFIED = "UNCLASSIFIED"

ALL_TAGS = [
    AFFILIATION, SUPPORT, CONCERN, DURATION, ASSUMPTION, MESSAGE_ACTION,
    EXPECTATION, POSITIVE_EVALUATION, SELF_STATE, JUDGMENT, DISSATISFACTION,
    FUTURE_EXPECTATION, CONDITION_PROMPT, SELF_ACCOUNTABILITY_PROMPT, INVITATION,
    ACTION_REPORT, ANTICIPATED_REACTION, CARE_FRAME, DELAY_JUSTIFICATION, SCARCITY,
    UNCERTAINTY, FUTURE_CONTACT, UNCLASSIFIED,
]

RELATIONSHIP_POSITIVE = {AFFILIATION, SUPPORT, CONCERN, CARE_FRAME, INVITATION}
EVALUATIVE_NEGATIVE = {JUDGMENT, DISSATISFACTION, ANTICIPATED_REACTION}
SPEAKER_STATE = {SELF_STATE, UNCERTAINTY, ASSUMPTION}
EXPLANATION_REQUEST = {CONDITION_PROMPT, SELF_ACCOUNTABILITY_PROMPT, INVITATION}
STRUCTURAL_CONTEXT = {DURATION, MESSAGE_ACTION, EXPECTATION, FUTURE_EXPECTATION, ACTION_REPORT, DELAY_JUSTIFICATION, SCARCITY, FUTURE_CONTACT}

TAG_GROUPS = {
    "RELATIONSHIP_POSITIVE": RELATIONSHIP_POSITIVE,
    "EVALUATIVE_NEGATIVE": EVALUATIVE_NEGATIVE,
    "SPEAKER_STATE": SPEAKER_STATE,
    "EXPLANATION_REQUEST": EXPLANATION_REQUEST,
    "STRUCTURAL_CONTEXT": STRUCTURAL_CONTEXT,
}
